### PR TITLE
Wip rgw new multisite

### PR DESCRIPTION
**Pull request by oritwas**
Changes needed for support new multisite implementation.

### CODE REVIEW

**Comment by yuriw** [comment]
@oritwas when we run this suite on jewel will `force-branch: ceph-master` have to be used as well?

**Comment by oritwas** [comment]
@yuriw at the moment yes, the jewel branch fails. 
In the future we will update the jewel branch and remove this constrain

**Comment by cbodley** [comment]
the multisite configuration steps look correct for both single- and multi-cluster setups

**Comment by cbodley** [comment]
@oritwas is on vacation this week, but I'd like to push this forward - any objections to merging?

**Pull request merged**
