### PR TITLE
jewel: multi-cluster support and rbd mirroring tests

### PR DESCRIPTION
**Pull request by jdurgin**
These are all clean cherry-picks of the multi-cluster branch and a couple follow-up fixes.

A couple suites scheduled to test this: 
http://pulpito.ceph.com/joshd-2016-05-20_11:40:22-rbd:mirror-jewel---basic-mira/ (using master workunits due to https://github.com/ceph/ceph/pull/9232)
http://pulpito.ceph.com/joshd-2016-05-20_11:41:24-teuthology:multi-cluster-jewel---basic-mira/

### CODE REVIEW

**Comment by dillaman** [comment]
@jdurgin Some failures that look like they are from within teuthology

**Comment by jdurgin** [comment]
whoops, those are all from an incomplete file in my working copy. The jobs from the committed test worked.

**Comment by jdurgin** [comment]
Looks like I need to fix something though - the teuthology multi-cluster suite failed

**Comment by jdurgin** [comment]
errors are from the suite itself - https://github.com/ceph/ceph-qa-suite/pull/1012 can be cherry-picked to jewel

**Pull request merged**
