### PR TITLE
Per Yehuda's comment in #12154, set s3tests branch to appropriate assignment  

### PR DESCRIPTION
**Pull request by yuriw**
@yehudasa Pls take a look and it OK I will cherry pink on hammer

Signed-off-by: Yuri Weinstein <yweinste@redhat.com>

### CODE REVIEW

**Comment by yehudasa** [comment]
@yuriw I don't think this is right. If upgrading from hammer to hammer it should be using the *hammer* branch. Beforehand it was supposed to use the firefly-original branch, but it was actually using the master branch. That was wrong. Something is broken so that it ignores that branch completely.

**Comment by yuriw** [comment]
@yehudasa see changes, pls

**Comment by yehudasa** [comment]
@yuriw I don't know if it's going to work or not. You'll have to run it to verify that it's actually doing the correct thing.

**Comment by yuriw** [comment]
@yehudasa ok running now http://pulpito.ceph.com/teuthology-2015-06-26_13:04:00-upgrade:hammer-hammer---basic-vps/

**Pull request closed without merging**
