### PR TITLE
tasks/cephfs: fix fuse force umount (again)

### PR DESCRIPTION
**Pull request by jcsp**
teuthology helpfully escapes things for us so
the \; didn't need the backslash.  The logic
was still falling over in some cases too.

Signed-off-by: John Spray <john.spray@redhat.com>

### CODE REVIEW

**Comment by alfredodeza** [comment]
ok to test

**Comment by alfredodeza** [comment]
@jcsp you will need to rebase this to get the `tox.ini` file that was just added in today

**Comment by zmc** [comment]
test this please

**Comment by gregsfortytwo** [comment]
Looks good, modulo any test issues when that gets working again.

**Comment by zmc** [comment]
test this please

**Comment by zmc** [comment]
test this please

**Comment by alfredodeza** [comment]
ok to test

**Pull request merged**
