### PR TITLE
jewel: ix console handling in tasks

### PR DESCRIPTION
**Pull request by dachary**
http://tracker.ceph.com/issues/17130

### CODE REVIEW

**Comment by dachary** [comment]
Testing at http://pulpito.ceph.com/loic-2016-08-25_06:53:48-powercycle-jewel-backports-testing-basic-smithi

**Comment by zmc** [comment]
I just cherry-picked these changes into jewel, infernalis, hammer and firefly

**Comment by dachary** [comment]
@zmc if that means this pull request no longer is necessary, feel free to close it.

**Comment by zmc** [comment]
It does - please let me know if pushing directly was a bad idea (the commits to master were reviewed in #1137)

**Pull request closed without merging**
