### PR TITLE
DNM: Use an NFS mount instead of virtio-9p in the qemu task

### PR DESCRIPTION
**Pull request by dachary**
Signed-off-by: Andrew Schoen <aschoen@redhat.com>
(cherry picked from commit 93f2bea3530a523c7b2ac0575033697cea893f2d)

### CODE REVIEW

**Comment by dachary** [comment]
@jdurgin I assume that's the commit you refer to with **backport andrew's fixing of the qemu task in ceph-qa-suite**. If feel freel to close the PR.

**Comment by andrewschoen** [comment]
@dachary my apologies, I should have cherry-picked this into all the other branches once it merged to master.

FWIW, this cherry-pick looks correct to me.  But, I'll wait on @jdurgin to verify this is what he wanted.

**Comment by dachary** [comment]
@andrewschoen no worries ;-) josh wants to wait until the firefly tests stabilize before backporting. It's a good thing you did not backport right away after all.

**Comment by jdurgin** [comment]
yup, that's what I meant. Thanks!

**Pull request merged**
