### PR TITLE
suites/fs: cephfs_journal_tool: wait for health after restart

### PR DESCRIPTION
**Pull request by ukernel**
Fixes: #14395
Signed-off-by: Yan, Zheng <zyan@redhat.com>

### CODE REVIEW

**Comment by jcsp** [comment]
LGTM

**Comment by gregsfortytwo** [comment]
Had to update, presumably you're both satisfied with that extra bit @jcsp @ukernel. ;)

**Comment by jcsp** [comment]
Sure

**Comment by gregsfortytwo** [comment]
http://pulpito.ceph.com/gregf-2016-01-18_18:01:09-fs-greg-fs-testing-118-1---basic-mira/

**Pull request merged**
