### PR TITLE
ceph_manager: Check for exit status 11 from ceph-objectstore-tool import

### PR DESCRIPTION
**Pull request by dzafman**

### CODE REVIEW

**Comment by dzafman** [comment]
@yuriw I'm not sure what branches this needs to be merged into.  I'm not familiar with what branches of ceph-qa-suite are involved during upgrade testing.

**Comment by yuriw** [comment]
@dzafman I think commits should go to hammer and master, but I will double check

**Comment by yuriw** [comment]
@dzafman I am not sure if you want me ro merge it or have somebody else to review ?

**Comment by dzafman** [comment]
@yuriw It isn't too complicated.  The python is valid code and it looks just like the other ignore case.

**Pull request merged**
