### PR TITLE
jewel: test: Eliminate racey scrubbing in scrub_test.py

### PR DESCRIPTION
**Pull request by dzafman**
Enhance get_pgid() to return passed value if it is already a pgid

Signed-off-by: David Zafman dzafman@redhat.com
(cherry picked from commit 29985efc7cdff252a822d31b5e18b9163849bc53)

Fixes: http://tracker.ceph.com/issues/16516

### CODE REVIEW

**Comment by dzafman** [comment]
Maybe we should add the following to the merge comment since the actual commit is a cherry-pick and it didn't have a bug associated with it.

Fixes: http://tracker.ceph.com/issues/16516

**Comment by dachary** [comment]
@dzafman it would not hurt to add the comment. But it's unlikely to help cross referencing because people are not usually doing that and we mostly rely on searching the commit and what not.

**Comment by smithfarm** [comment]
@dzafman Could you put the "Fixes: ..." line in the commit message? After the "(cherry picked ...)" line with an intervening blank line, perhaps?

**Comment by dzafman** [comment]
Added "Fixes:..." to the commit.

**Comment by smithfarm** [comment]
If I schedule a jewel run before this is merged, I'll definitely include it.

**Comment by smithfarm** [comment]
This is just a small run, but I'll include it here anyway:

`cw -v ceph-qa-suite --teuthology-git-url http://github.com/SUSE/teuthology --teuthology-branch wip-openstack-zypper-capabilities --suite-branch wip-16516 --ceph jewel --suite rados/basic --subset 0/2000`

**running** http://158.69.85.90:8081/ubuntu-2016-09-14_11:04:25-rados:basic-jewel---basic-openstack/

**Comment by smithfarm** [comment]
@dzafman This patch doesn't seem to fix the problem, see:

http://158.69.85.90:8081/ubuntu-2016-09-14_11:04:25-rados:basic-jewel---basic-openstack/9/

I double-checked on the teuthology VM and your patch is definitely there.

**Comment by smithfarm** [comment]
@dzafman I went ahead and cherry-picked 4d0c668e as called for in http://tracker.ceph.com/issues/16516#note-10

I will be running a full rados suite in Sepia soon, to test some teuthology patches - I'll run it against this PR (`--ceph wip-16516`).

**Comment by dzafman** [comment]
@yuriw On the next Jewel run include this branch in the ceph-qa-suite being used and if it works right then merge this backport.

**Comment by smithfarm** [comment]
Sorry, I got sidetracked :-/

**Comment by yuriw** [comment]
@smithfarm I assume you are running it as @dzafman requested, otherwise let me know, thx !

**Comment by smithfarm** [comment]
@yuriw No, I don't plan any jewel test runs in the near future.

**Comment by yuriw** [comment]
@dzafman @smithfarm 
Scheduled run with `--ceph jewel --suite-branch wip-16516`
http://pulpito.ceph.com/yuriw-2016-10-31_20:37:33-rados-jewel-distro-basic-smithi/

**Comment by dzafman** [comment]
@vasukulkarni I updated this pull request which reverts your partial change and has the cherry-pick of the master commit.  I don't think the other part of that commit is important but it keeps jewel cleaner relative to master.

**Comment by vasukulkarni** [comment]
@dzafman thanks

**Pull request merged**
