### PR TITLE
tasks/cephfs: add TestForwardScrub.test_backtrace_repair

### PR DESCRIPTION
**Pull request by jcsp**
Fixes: http://tracker.ceph.com/issues/17639
Signed-off-by: John Spray <john.spray@redhat.com>

### CODE REVIEW

**Comment by jcsp** [comment]
Tests https://github.com/ceph/ceph/pull/11578

**Comment by gregsfortytwo** [comment]
LGTM.

**Comment by gregsfortytwo** [comment]
Test this please

**Comment by ukernel** [comment]
I don't see repair backtrace function in scrub code. It's likely the backtrace get checked/fixed when fetching dirfrag.

**Comment by jcsp** [comment]
Test passing here: http://pulpito.ceph.com/jspray-2016-10-23_18:55:33-fs-wip-jcsp-testing-20161020b-distro-basic-mira/ (but hitting the new log message, I have updated this PR to whitelist it)

**Comment by ukernel** [comment]
Test case fixed.

**Pull request merged**
