### PR TITLE
tasks/cephfs: support old mdsmap command during setup

### PR DESCRIPTION
**Pull request by jcsp**
While Filesystem at large requires the new commands, for
use from the `ceph` task we must support old style commands,
as the ceph task is used to instantiate old clusters during
upgrade testing.

Fixes: #15124, #15049, #15106

Signed-off-by: John Spray <john.spray@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
tox sez

./tasks/cephfs/filesystem.py:380:34: F821 undefined name 'errno'
./tasks/cephfs/filesystem.py:406:46: F821 undefined name 'errno'

otherwise lgtm

**Comment by jcsp** [comment]
tox is correct!  I'm having a quick check that this really works here: http://pulpito.ceph.com/jspray-2016-03-15_06:16:01-rados:singleton-nomsgr-jewel---basic-mira

**Comment by jcsp** [comment]
Passing here (along with #880):
http://pulpito.ceph.com/jspray-2016-03-15_10:04:24-rados:singleton-nomsgr-jewel---basic-mira/

**Comment by gregsfortytwo** [comment]
Yep, I had it in the (all-green!) http://pulpito.ceph.com/gregf-2016-03-15_04:07:43-fs-greg-fs-testing-314---basic-mira/

And in upgrade testing with the qa-suite updates it did...better than zero, which is apparently the current state of master (http://pulpito.ceph.com/gregf-2016-03-15_12:49:59-upgrade:infernalis-x-greg-fs-testing-314---basic-mira)

**Pull request merged**
