### PR TITLE
rados: avoid xenial for upgrade tests

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by djgalloway** [comment]
Does this encompass the tests that failed as reported in http://tracker.ceph.com/issues/18089 too?

**Comment by liewegas** [comment]
as far as i can tell

**Comment by theanalyst** [comment]
I think the  symlinks are wrong in the second commit.. pushed https://github.com/ceph/ceph-qa-suite/commit/3e1c302b9df1a689ac70a5b77b33f142027bed69 (as branch jewel-avoid-xenial-upgrade) to run the tests

**Comment by theanalyst** [comment]
I don't think my commit fixed the issue yet, scheduling a suite with that still ended up with the same failure

**Pull request merged**
