### PR TITLE
upgrade: use infernalis instead of hammer for rbd tests

### PR DESCRIPTION
**Pull request by dachary**
There are only few differences at the moment but it may be confusing
later on if a bug is fixed in the infernalis workunits later on.

Signed-off-by: Loic Dachary <loic@dachary.org>

### CODE REVIEW

**Comment by dillaman** [comment]
I always thought the purpose of these tests were to ensure that old versions of librbd still function with a newer OSD (i.e. we didn't break something in the RBD class methods or the OSD didn't change semantics).

**Comment by dachary** [comment]
@dillaman it's also my understanding: in the jewel branch of ceph-qa-suite, the infernalis-x verifies that installing infernalis and upgrading to the latest jewel while using librbd from infernalis works as expected. The workunit of the jewel branch should be used for that purpose, I think. Not the workunit from the hammer branch. Or am I missing something ?

**Comment by jdurgin** [comment]
@dachary I think it should be the workunit from the infernalis branch for this suite, since it's testing the original client continues to behave as the cluster is upgraded. The client is never upgraded from infernalis in this suite, though a final 'upgrade client.0 and run jewel tests' might be a good addition.

**Comment by yuriw** [comment]
@dachary it'd be great to use `teuthology-describe-tests` to add descriptions for cases like this for future reference :+1:

**Comment by dachary** [comment]
@yuriw there are descriptions already :-)

**Comment by dachary** [comment]
@jdurgin @dillaman updated and repushed with s/hammer/infernalis/ as suggested.

**Pull request merged**
