### PR TITLE
suites: invoke libcephfs python tests

### PR DESCRIPTION
**Pull request by jcsp**
Depends on https://github.com/ceph/ceph/pull/7901

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
@jcsp, tried this in http://pulpito.ceph.com/gregf-2016-03-09_00:11:22-fs-greg-fs-testing-38-1---basic-mira/ and it seems to have failed entirely (errno 39, ENOTEMPTY...on directory cleanup, maybe?).

**Comment by jcsp** [comment]
Hmm, should work if we remove the fuse task; the python tests work in the root of the filesystem, so they were tripping up on the client.0/ folder that the workunit task creates.

Updated.

**Comment by gregsfortytwo** [comment]
Still busted (pretty sure I built the branch properly): http://pulpito.ceph.com/gregf-2016-03-10_23:53:12-fs-greg-fs-testing-310-1---basic-mira/

**Comment by jcsp** [comment]
updated https://github.com/ceph/ceph/pull/7901 to hopefully fix this

**Comment by jcsp** [comment]
Passing here: http://qa-proxy.ceph.com/teuthology/jspray-2016-03-15_08:58:50-fs:basic-wip-pycephfs-flock---basic-mira/62101/teuthology.log

**Pull request merged**
