### PR TITLE
tasks: fix intermittent failure in TestFlush

### PR DESCRIPTION
**Pull request by jcsp**
This was an overly strict success condition: the
flush operation doesn't promise to leave you an empty
journal, it promises that anything in the journal
before the flush will be flushed.

Fixes: #10712
Signed-off-by: John Spray <john.spray@redhat.com>

### CODE REVIEW

**Comment by jcsp** [comment]
ok to test

**Comment by gregsfortytwo** [comment]
Looks good.

**Comment by gregsfortytwo** [comment]
ok to test

**Comment by andrewschoen** [comment]
ok to test

**Comment by alfredodeza** [comment]
test this please

**Comment by alfredodeza** [comment]
add to whitelist

**Pull request merged**
