### PR TITLE
hammer: Testing: SIGABRT in TrackedOp::dump() via dump_ops_in_flight()

### PR DESCRIPTION
**Pull request by dzafman**
Backport 3 pull requests and add fix specifically for Hammer not to use osd.\* since it crashes the command.

ceph/ceph-qa-suite#344
ceph/ceph-qa-suite#911
ceph/ceph-qa-suite#1122

### CODE REVIEW

**Comment by dzafman** [comment]
Only merge with ceph/ceph#10255

**Comment by dzafman** [comment]
For some reason I got 11 crashes of python during a rados:thrash run.  Using _strings_ on the cores revealed a common strings:

/usr/bin/python /usr/bin/ceph tell osd.* injectargs --osd_enable_op_tracker=...

http://pulpito.ceph.com/dzafman-2016-07-12_16:03:42-rados:thrash-wip-zafman-testing-hammer---basic-smithi/

**Comment by dzafman** [comment]
The last 2 commits come from ceph/ceph-qa-suite#1122 which hasn't merged yet

**Comment by dzafman** [comment]
Passed with latest version:
http://pulpito.ceph.com/dzafman-2016-08-18_22:32:36-rados:thrash-wip-zafman-testing-hammer-distro-basic-smithi/

**Comment by smithfarm** [comment]
@dzafman Can we remove DNM now? I have prepared a `hammer-backports` integration branch - see http://tracker.ceph.com/issues/17151#note-6 - that includes ceph/ceph#10255 and IIUC I will need this PR to test it.

**Comment by dzafman** [comment]
Superseded by ceph/ceph-qa-suite#1278

**Pull request closed without merging**
