### PR TITLE
rgw: we don't support btrfs any more

### PR DESCRIPTION
**Pull request by oritwas**
Signed-off-by: Orit Wasserman <owasserm@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
ok with me

**Comment by liewegas** [comment]
although i don't think we've already decided "we don't support btrfs".  i'm ok with deciding that tho with kraken+.

**Comment by oritwas** [comment]
@yehudasa , can we merge it for master?

**Comment by yehudasa** [comment]
@oritwas sure

**Pull request merged**
