### PR TITLE
tasks/cephfs: Enable killpoint tests for multi-mds recovery

### PR DESCRIPTION
**Pull request by vishalkanaujia**
The test verify directory export code path with killpoints.

Fixes: http://tracker.ceph.com/issues/17835
Signed-off-by: Vishal Kanaujia <vishal.kanaujia@sandisk.com>

### CODE REVIEW

**Comment by vishalkanaujia** [comment]
The test passes for killpoint 1...10, and 12. It fails for kill point 11 and 13 with following error:

2016-12-23 16:51:04.269288 7f93b9a7b700  1 mds.a asok_command: export dir (starting...)
2016-12-23 16:51:04.269311 7f93b9a7b700 -1 mds.0.182 bad export_dir path dirfrag frag_t() or dir not auth
2016-12-23 16:51:04.269321 7f93b9a7b700  1 mds.a asok_command: export dir (complete)

After verification, we need to file a new bug for the above failure.

**Comment by vishalkanaujia** [comment]
@jcsp Request you to review the changes.

**Comment by tchaikov** [comment]
@vishalkanaujia ceph-qa-suite is moved into ceph project. you might want to send your pull request to it instead. see https://github.com/ceph/ceph/tree/master/qa/tasks/cephfs

**Comment by vishalkanaujia** [comment]
@tchaikov Thanks for the suggestion. I moved the PR to ceph repository. Closing this PR.

**Pull request closed without merging**
