### PR TITLE
Fix experimental feature override makes user config useless

### PR DESCRIPTION
**Pull request by yuyuyu101**
Signed-off-by: Haomai Wang haomaiwang@gmail.com

### CODE REVIEW

**Comment by dachary** [comment]
That will make shec tests fail.

**Comment by yuyuyu101** [comment]
@dachary do you have other ideas? Otherwise, I can't run async-messenger tests which reference to this yaml.

**Comment by athanatos** [comment]
Annoying.  You modify the ceph task to check for an experiemental_features list at the same level as the config dict.  Then, the override merge logic would give you the union of the lists and would presumably behave better.  You could probably also just add async messenger to everywhere that mentions the expermental features config value.

**Comment by yuyuyu101** [comment]
@athanatos updated

**Comment by dachary** [comment]
@yuyuyu101 looks great :-) Could you run at least one job including this change and append the URL of the result here ? When done it's good to merge.

**Comment by yuyuyu101** [comment]
@dachary it(http://pulpito.ceph.com/haomai-2015-08-04_20:31:08-rados-master-distro-basic-multi/) showed no failed job related to this job. :-)

**Comment by dachary** [comment]
@yuyuyu101 could you please link to the specific job that contains the file modified by this patch ?

**Comment by yuyuyu101** [comment]
@dachary just like this(http://pulpito.ceph.com/haomai-2015-08-04_20:31:08-rados-master-distro-basic-multi/999879/) it will have "shec ms-type-async"

**Comment by dachary** [comment]
@yuyuyu101 is there a successful job with **shec ms-type-async** ?

**Comment by liewegas** [comment]
On Wed, 5 Aug 2015, Haomai Wang wrote:
> @dachary just like this(http://pulpito.ceph.com/haomai-2015-08-04_20:31:08-rados-master-distro-basic-multi/999879/) it will have "shec
> ms-type-async"

we could make a (perhaps undocumented?) feature that a '*' value will 
match any experimental feature for the purposes of qa...

**Comment by yuyuyu101** [comment]
@dachary like this(http://pulpito.ceph.com/haomai-2015-08-04_20:31:08-rados-master-distro-basic-multi/999905/) :-)

**Pull request merged**
