### PR TITLE
Add testing for CephFSVolumeClient

### PR DESCRIPTION
**Pull request by jcsp**

### CODE REVIEW

**Comment by jcsp** [comment]
Linter unhappy, will fix in subsequent update

**Comment by gregsfortytwo** [comment]
@jcsp this is still not linter clean (looks like just an extra include), in addition to the PG creation problems you've got with the main PR. :)

**Comment by gregsfortytwo** [comment]
@jcsp there are some merge conflicts here and against master (and possibly one of the other branches I was testing in greg-fs-speculative commit 917896348801246f1f426ae852c4702a29b84b03). I resolved in the merge 450ffb69063bd40a16909c2ec986427cde31e1d1, but you might want to check those and rebase this PR.

**Comment by jcsp** [comment]
Mergeable again.  The conflict was just because this branch and wip-root-metadata both had the "generate mount paths on the fly" commit.

**Pull request merged**
