### PR TITLE
test: Eliminate racey scrubbing in scrub_test.py

### PR DESCRIPTION
**Pull request by dzafman**
Enhance get_pgid() to return passed value if it is already a pgid

Signed-off-by: David Zafman <dzafman@redhat.com>

### CODE REVIEW

**Comment by dzafman** [comment]
Testing passed: http://pulpito.ceph.com/dzafman-2016-06-10_11:19:54-rados-wip-zafman-testing---basic-smithi/

**Comment by dzafman** [comment]
@tchaikov This is ready to be reviewed and merged.

**Comment by dzafman** [comment]
@tchaikov This needs to be fixed,

**Comment by dzafman** [comment]
@tchaikov Now this time for sure this is ready:

http://pulpito.ceph.com/dzafman-2016-06-15_23:31:36-rados-wip-zafman-testing---basic-smithi/

**Comment by tchaikov** [comment]
will review it tmr.

**Comment by tchaikov** [comment]
thanks for fixing this!

**Pull request merged**
