### PR TITLE
buildpackages: openstack image names not unique.

### PR DESCRIPTION
**Pull request by dachary**

### CODE REVIEW

**Comment by dachary** [comment]
This is a rebase of https://github.com/ceph/ceph-qa-suite/pull/763 which I overlooked for a very long time. Does it look ok to you ?

**Comment by robbat2** [comment]
@dachary passes eyeball test

**Comment by dachary** [comment]
Something has changed in how openstack image list name fields:

<pre>
(virtualenv)ubuntu@teuthology:~$ openstack image list -f json --long
..
  {
    "Status": "active", 
    "Name": "Centos 7", 
    "Container Format": "bare", 
    "Tags": "", 
    "Disk Format": "raw", 
    "Visibility": "public", 
    "Project": "9386d7837e514fc080082efe4892af59", 
    "Protected": false, 
    "ID": "c06fe6f2-3567-4ec3-8562-4cecf4044c30", 
    "Size": 2149580800
  }
(virtualenv)ubuntu@teutholoy:~$ openstack image show c06fe6f2-3567-4ec3-8562-4cecf4044c30
+------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Field            | Value                                                                                                                                                                      |
+------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| checksum         | 4fb120a80085a8ccd679488cb497d7fd                                                                                                                                           |
| container_format | bare                                                                                                                                                                       |
| created_at       | 2015-04-28T13:41:57Z                                                                                                                                                       |
| disk_format      | raw                                                                                                                                                                        |
| file             | /v2/images/c06fe6f2-3567-4ec3-8562-4cecf4044c30/file                                                                                                                       |
| id               | c06fe6f2-3567-4ec3-8562-4cecf4044c30                                                                                                                                       |
| min_disk         | 0                                                                                                                                                                          |
| min_ram          | 0                                                                                                                                                                          |
| name             | Centos 7                                                                                                                                                                   |
| owner            | 9386d7837e514fc080082efe4892af59                                                                                                                                           |
| properties       | direct_url='rbd://fd2b710c-9efb-400e-bbc0-9f95db1c2535/images/c06fe6f2-3567-4ec3-8562-4cecf4044c30/snap', locations='[{u'url': u'rbd://fd2b710c-9efb-400e-                 |
|                  | bbc0-9f95db1c2535/images/c06fe6f2-3567-4ec3-8562-4cecf4044c30/snap', u'metadata': {}}]'                                                                                    |
| protected        | False                                                                                                                                                                      |
| schema           | /v2/schemas/image                                                                                                                                                          |
| size             | 2149580800                                                                                                                                                                 |
| status           | active                                                                                                                                                                     |
| tags             |                                                                                                                                                                            |
| updated_at       | 2015-04-28T13:42:52Z                                                                                                                                                       |
| visibility       | public                                                                                                                                                                     |
+------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
</pre>

**Comment by robbat2** [comment]
@dachary which commit was f75b442; because that's not the original ID I gave it, and it's gone from history here on GitHub :-(.

**Pull request merged**
