### PR TITLE
Added v0.94.3 to the mix

### PR DESCRIPTION
**Pull request by yuriw**
@liewegas @tmuthamizhan Pls review and merge

Signed-off-by: Yuri Weinstein <yweinste@redhat.com>

### CODE REVIEW

**Comment by tmuthamizhan** [comment]
the comment for this PR should be "added v0.94.3 and v0.94.5 to the mix" [please note the version numbers mismatch]
also, the extension of the yaml files should be ".yaml" and NOT ".yml"

**Comment by yuriw** [comment]
@tmuthamizhan fixed typos thx for good catch

**Comment by tmuthamizhan** [comment]
ok, one more thing is that - latest hammer is v0.94.5, so you dont have to add that to the mix as that would be upgrading from v0.94.5 to v0.94.5 itself, instead you should probably add v0.94.4

**Comment by yuriw** [comment]
@tmuthamizhan 
I think that latest hammer is not always equal to the last point release v0.94.5, so suggest to keep it, but will remove if forced :) 
And we have already v0.94.4
As of now we have:  `v0.94.2 v0.94.3  v0.94.4  v0.94.5`

**Comment by yuriw** [comment]
If you think about it then upgrading from `latest giant` to `v0.94.2 v0.94.3 v0.94.4 v0.94.5` should always pass, because there is no changes in the code are introduced. 
So may get by with upgrading `v0.94.5 -> hammer`?!
Thinking aloud about usefulness of those type of suites, @tmuthamizhan @liewegas  pls comment.

**Pull request merged**
