### PR TITLE
erasure-code: test larger k/m values

### PR DESCRIPTION
**Pull request by ghost**
Signed-off-by: Loic Dachary ldachary@redhat.com

### CODE REVIEW

**Comment by liewegas** [comment]
@dachary should we test and merge this?

**Comment by dachary** [comment]
<pre>
teuthology-suite -k distro --priority 1000 --suite rados/thrash-erasure-code-big --subset $(expr $RANDOM % 2000)/2000 --suite-branch master --email loic@dachary.org --ceph master --machine-type smithi
</pre>

* **running** http://pulpito.ceph.com/loic-2016-12-06_06:18:19-rados:thrash-erasure-code-big-master-distro-basic-smithi

**Comment by dachary** [comment]
<pre>
teuthology-suite -k distro --priority 1000 --suite rados/thrash-erasure-code-big --subset $(expr $RANDOM % 2000)/2000 --suite-branch wip-large-erasure-code-k-m --email loic@dachary.org --ceph master --machine-type smithi
</pre>

* **running**

**Comment by dachary** [comment]
The previous run failed because of packaging problems.
<pre>
teuthology-suite  --newest 10 -k distro --priority 1000 --suite rados/thrash-erasure-code-big --subset $(expr $RANDOM % 2000)/2000 --suite-branch wip-large-erasure-code-k-m --email loic@dachary.org --ceph master --machine-type smithi
</pre>

* **running** http://pulpito.ceph.com/loic-2016-12-14_15:53:25-rados:thrash-erasure-code-big-master-distro-basic-smithi/

**Comment by liewegas** [comment]
ceph-qa-suite is now merged into ceph.git.  Please resubmit this PR against ceph.git.

**Pull request closed without merging**
