### PR TITLE
upgrade: disable ceph-objectstore-tool test in infernalis-x

### PR DESCRIPTION
**Pull request by smithfarm**
Fixes: http://tracker.ceph.com/issues/17683

### CODE REVIEW

**Comment by smithfarm** [comment]
@yuriw I pushed this to ceph/ceph-qa-suite as `wip-17683` if you'd like to test it

**Comment by smithfarm** [comment]
@dachary Care to review?

**Comment by jdurgin** [comment]
Yeah, looks good to me!

**Comment by dachary** [comment]
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Comment by yuriw** [comment]
@smithfarm we may want bac4fa4589c2db5f2986eab79611c17ea73f4dc6 on master as well

**Comment by smithfarm** [comment]
**running** http://pulpito.ceph.com/smithfarm-2016-11-12_19:59:10-upgrade:infernalis-x-jewel-distro-basic-vps/

**Comment by smithfarm** [comment]
@yuriw: We would only want the disable ceph-objectstore-tool test in master if we were going to test infernalis -> kraken upgrades. Since that's not going to happen, I would keep this change in jewel only.

**Comment by yuriw** [comment]
@smithfarm true, ack

**Comment by smithfarm** [comment]
@jdurgin @dachary @yuriw The first test run on the "thrashosds: add option to disable ceph-objectstore-tool test" patch was unsatisfactory - three of the five jobs affected ran for 12 hours and then failed. So I changed the logic slightly - see cf41f56

As you can see above, I did a second run with much better results. The jobs that ran for 12 hours and failed before now run 6 hours and succeed. This is better, but there would still seem to be room for improvement as these jobs produce huge logs (e.g. 4.2G) - isn't that excessive?

**Comment by smithfarm** [comment]
I now see there is already infrastructure for disabling the ceph-objectstore-tool test in the config - see https://github.com/ceph/ceph-qa-suite/blob/jewel/tasks/ceph_manager.py#L141-L154 - so I modified the PR to use that, instead.

**running** http://pulpito.ceph.com/smithfarm-2016-11-13_07:35:00-upgrade:infernalis-x-jewel-distro-basic-vps/

**Comment by smithfarm** [comment]
The dead job was caused by an OSD crash:

```
2016-11-13T10:18:19.346 INFO:tasks.ceph.osd.0.vpm125.stderr:*** Caught signal (Segmentation fault) **
2016-11-13T10:18:19.346 INFO:tasks.ceph.osd.0.vpm125.stderr: in thread 7f9e6f8ba700 thread_name:tp_osd
2016-11-13T10:18:19.729 INFO:tasks.ceph.osd.0.vpm125.stderr: ceph version 10.2.3-358-g427f357 (427f357f0eed32c9ce17590ae9303a94e8b710e7)
2016-11-13T10:18:19.729 INFO:tasks.ceph.osd.0.vpm125.stderr: 1: (()+0x8f24a2) [0x7f9e8e2054a2]
2016-11-13T10:18:19.729 INFO:tasks.ceph.osd.0.vpm125.stderr: 2: (()+0x10330) [0x7f9e8c5bc330]
2016-11-13T10:18:19.729 INFO:tasks.ceph.osd.0.vpm125.stderr: 3: (crush_find_rule()+0x29) [0x7f9e8e378729]
2016-11-13T10:18:19.730 INFO:tasks.ceph.osd.0.vpm125.stderr: 4: (OSDMap::_pg_to_osds(pg_pool_t const&, pg_t, std::vector<int, std::allocator<int> >*, int*, unsigned int*) const+0x64) [0x7f9e8e2b8b84]
2016-11-13T10:18:19.730 INFO:tasks.ceph.osd.0.vpm125.stderr: 5: (OSDMap::_pg_to_up_acting_osds(pg_t const&, std::vector<int, std::allocator<int> >*, int*, std::vector<int, std::allocator<int> >*, int*) const+0xf1) [0x7f9e8e2bb6c1]
2016-11-13T10:18:19.730 INFO:tasks.ceph.osd.0.vpm125.stderr: 6: (OSD::advance_pg(unsigned int, PG*, ThreadPool::TPHandle&, PG::RecoveryCtx*, std::set<boost::intrusive_ptr<PG>, std::less<boost::intrusive_ptr<PG> >, std::allocator<boost::intrusive_ptr<PG> > >*)+0x207) [0x7f9e8dca8bd7]
2016-11-13T10:18:19.730 INFO:tasks.ceph.osd.0.vpm125.stderr: 7: (OSD::process_peering_events(std::list<PG*, std::allocator<PG*> > const&, ThreadPool::TPHandle&)+0x1a1) [0x7f9e8dcbd191]
2016-11-13T10:18:19.730 INFO:tasks.ceph.osd.0.vpm125.stderr: 8: (OSD::PeeringWQ::_process(std::list<PG*, std::allocator<PG*> > const&, ThreadPool::TPHandle&)+0x12) [0x7f9e8dd05102]
2016-11-13T10:18:19.730 INFO:tasks.ceph.osd.0.vpm125.stderr: 9: (ThreadPool::worker(ThreadPool::WorkThread*)+0xa5e) [0x7f9e8e2ea74e]
2016-11-13T10:18:19.730 INFO:tasks.ceph.osd.0.vpm125.stderr: 10: (ThreadPool::WorkThread::entry()+0x10) [0x7f9e8e2eb630]
2016-11-13T10:18:19.730 INFO:tasks.ceph.osd.0.vpm125.stderr: 11: (()+0x8184) [0x7f9e8c5b4184]
2016-11-13T10:18:19.730 INFO:tasks.ceph.osd.0.vpm125.stderr: 12: (clone()+0x6d) [0x7f9e8a6e037d]
```

**Comment by smithfarm** [comment]
@yuriw Ready to merge?

**Comment by smithfarm** [comment]
[(issue#17683) "ceph-objectstore-tool apply-layout-settings failed with 1" in upgrade:infernalis-x-jewel-distro-basic-vps](https://trello.com/c/b36TjNlh/2170-issue-17683-ceph-objectstore-tool-apply-layout-settings-failed-with-1-in-upgrade-infernalis-x-jewel-distro-basic-vps)

**Pull request merged**
