### PR TITLE
osd_recovery: add delay to ensure maps propogate

### PR DESCRIPTION
**Pull request by athanatos**
Signed-off-by: Samuel Just <sjust@redhat.com>

### CODE REVIEW

**Comment by athanatos** [comment]
Tested: sjust@teuthology:/a/samuelj-2016-05-16_20:02:21-rados-wip-sam-testing-distro-basic-smithi

**Comment by smithfarm** [comment]
@athanatos: OK to backport this to jewel and hammer? I have a test failure[1] that is failing in the `assert not manager.is_recovered()` and it looks like a timing issue.

[1] http://158.69.78.47:8081/ubuntu-2016-07-27_15:27:10-rados-hammer-backports---basic-openstack/61/

**Comment by athanatos** [comment]
@smithfarm Yeah, go for it.

**Comment by smithfarm** [comment]
Backports: #1101, #1102

**Pull request merged**
