### PR TITLE
tasks/cephfs: update failover test for standby changes

### PR DESCRIPTION
**Pull request by jcsp**
Previously, an MDS could be used as a replay even
if it had "standby replay = false", this is changed
now so that replays will only happen explicitly.

Signed-off-by: John Spray <john.spray@redhat.com>

### CODE REVIEW

**Comment by jcsp** [comment]
DNM until https://github.com/ceph/ceph/pull/8300

**Comment by gregsfortytwo** [comment]
@jcsp, do you think this is good to go now?
I haven't reviewed it yet but I want to make sure it shouldn't be DNM any more.

**Comment by jcsp** [comment]
Yes, please go ahead and review

**Comment by jcsp** [comment]
Passing tests here: http://pulpito.ceph.com/jspray-2016-05-12_04:34:36-fs-wip-jcsp-testing-20160511---basic-smithi/

@gregsfortytwo since test_standby_for_name fails without this, should probably err on the side of merging this fairly soon

**Pull request merged**
