### PR TITLE
Jewel 14805

### PR DESCRIPTION
**Pull request by ukernel**

### CODE REVIEW

**Comment by ukernel** [comment]
http://pulpito.ceph.com/zyan-2016-03-01_20:05:19-hadoop-jewel-testing-basic-mira/

**Comment by gregsfortytwo** [comment]
@noahdesu, you'll want to note this and http://tracker.ceph.com/issues/14805.

**Comment by noahdesu** [comment]
Thanks for the reference! Added to my backlog. HotStorage almost done!

**Comment by gregsfortytwo** [comment]
Now that John got it through my head what's going on here, I ran this through some tests and it looks good. We did get a terasort failure in http://pulpito.ceph.com/gregf-2016-03-23_23:08:55-hadoop-greg-fs-testing-323-3---basic-mira/, but it's inconsistent so clearly its own bug.

**Comment by noahdesu** [comment]
Ugh this looks familiar. It's at the end of the job. Looks like a race since hadoop is probably constructed to make sure the directory is empty.

```
2016-03-24T00:28:55.611 INFO:tasks.workunit.client.0.mira054.stderr:16/03/24 07:28:55 INFO mapreduce.Job: Job job_1458804250318_0002 failed with state FAILED due to: Job commit failed: java.io.IOException: Directory not empty
2016-03-24T00:28:55.611 INFO:tasks.workunit.client.0.mira054.stderr:	at com.ceph.fs.CephMount.native_ceph_rmdir(Native Method)
2016-03-24T00:28:55.612 INFO:tasks.workunit.client.0.mira054.stderr:	at com.ceph.fs.CephMount.rmdir(CephMount.java:406)
2016-03-24T00:28:55.612 INFO:tasks.workunit.client.0.mira054.stderr:	at org.apache.hadoop.fs.ceph.CephTalker.rmdir(CephTalker.java:223)
2016-03-24T00:28:55.612 INFO:tasks.workunit.client.0.mira054.stderr:	at org.apache.hadoop.fs.ceph.CephFileSystem.delete(CephFileSystem.java:628)
2016-03-24T00:28:55.612 INFO:tasks.workunit.client.0.mira054.stderr:	at org.apache.hadoop.fs.ceph.CephFileSystem.delete(CephFileSystem.java:624)
```

**Pull request merged**
