### PR TITLE
Added excluded packages "'libcephfs-devel','libcephfs-dev'"

### PR DESCRIPTION
**Pull request by yuriw**
Fixes http://tracker.ceph.com/issues/17902
Signed-off-by: Yuri Weinstein <yweinste@redhat.com>

### CODE REVIEW

**Comment by yuriw** [comment]
testing - http://pulpito.front.sepia.ceph.com:80/yuriw-2016-11-15_17:49:33-upgrade:jewel-x-master-distro-basic-vps/

**Comment by tmuthamizhan** [comment]
@yuriw - maybe we need to exclude packages: ceph-mgr and libcephfs2 as well. some of the tests are failing with that error.

**Comment by tmuthamizhan** [comment]
@yuriw  , also for install.upgrade, exclude_packages should be under install.upgrade and not mons.
ex: 
- install.upgrade:
      exclude_packages:
      - ceph-mgr
      - libcephfs2
      - libcephfs-devel
      - libcephfs-dev
      mon.a:
         branch: jewel

**Comment by yuriw** [comment]
test this please

**Comment by yuriw** [comment]
http://pulpito.ceph.com/yuriw-2016-11-17_16:41:32-upgrade:jewel-x-master-distro-basic-smithi/

passed

**Pull request merged**
