### PR TITLE
[DNM]tasks/cephfs: cover snaps in test_strays

### PR DESCRIPTION
**Pull request by jcsp**
Signed-off-by: John Spray <john.spray@redhat.com>

### CODE REVIEW

**Comment by jcsp** [comment]
This covers the following commits:

<pre>
commit 511435f568115637dfd1901584d206e44072b1be
Author: Yan, Zheng <zyan@redhat.com>
Date:   Mon Nov 16 21:08:00 2015 +0800

    client: avoid creating orphan object in Client::check_pool_perm()
    
    Fixes: #13782
    Signed-off-by: Yan, Zheng <zyan@redhat.com>

commit 9dfae25196f82bbaae93bbed0ff336b53e9921d6
Author: John Spray <john.spray@redhat.com>
Date:   Mon Nov 16 10:57:56 2015 +0000

    mon: don't require OSD W for MRemoveSnaps
    
    Use ability to execute "osd pool rmsnap" command
    as a signal that the client should be permitted
    to send MRemoveSnaps too.
    
    Note that we don't also require the W ability,
    unlike Monitor::_allowed_command -- this is slightly
    more permissive handling, but anyone crafting caps
    that explicitly permit "osd pool rmsnap" needs to
    know what they are doing.
    
    Signed-off-by: John Spray <john.spray@redhat.com>

commit 460c74a0b872336a7279f0b40b17ed672b6e15a1
Author: Yan, Zheng <zyan@redhat.com>
Date:   Thu Nov 12 21:57:27 2015 +0800

    mds: properly set STATE_STRAY/STATE_ORPHAN for stray dentry/inode
    
    Fixes: #13777
    Signed-off-by: Yan, Zheng <zyan@redhat.com>
</pre>

They're all merged apart from https://github.com/ceph/ceph/pull/6601

**Comment by jcsp** [comment]
DNM because this is now based on some of the other PRs (the update to run_shell that this test needed touched them too).  Merge this after them.

**Comment by gregsfortytwo** [comment]
@jcsp Can you list out the dependencies? ;) Easier to prioritize stuff that way.

**Comment by jcsp** [comment]
I didn't list out dependencies because this was just done on the tip of my testing branch.  By having a quick look at the patch, I can tell you that it's just waiting for https://github.com/ceph/ceph-qa-suite/pull/709, which in turn doesn't have anything blocking it afaik.

**Pull request merged**
