### PR TITLE
tasks/cephfs: add TestStraysStandby

### PR DESCRIPTION
**Pull request by jcsp**
Tests that standby replay daemons kick out cache
entries that are no longer needed.

Fixes: http://tracker.ceph.com/issues/16919
Signed-off-by: John Spray john.spray@redhat.com

### CODE REVIEW

**Comment by jcsp** [comment]
Tests https://github.com/ceph/ceph/pull/10606

**Comment by gregsfortytwo** [comment]
LGTM, testing

**Comment by gregsfortytwo** [comment]
This doesn't work: http://pulpito.ceph.com/gregf-2016-08-24_23:15:57-fs-greg-fs-testing-824---basic-mira/384085/

**Comment by gregsfortytwo** [comment]
Sorry, it's not the immediate test failing; http://pulpito.ceph.com/gregf-2016-08-25_19:08:49-fs-greg-fs-testing-825---basic-mira/385454/ has a problem with the MDS not shutting down when told. My best guess right now is it's the Ceph change associated with this test PR though...trying again.

**Comment by jcsp** [comment]
Hmm, this is failing /a/jspray-2016-10-10_10:53:06-fs:recovery-master-distro-basic-mira/465247/teuthology.log (assigning to self)

**Comment by jcsp** [comment]
Depends on https://github.com/ceph/ceph/pull/12077

**Comment by gregsfortytwo** [comment]
ping @jcsp, that dependency has merged

**Comment by liewegas** [comment]
ceph-qa-suite is now merged into ceph.git.  Please resubmit this PR against ceph.git.

**Pull request closed without merging**
