### PR TITLE
add erasure code repair / scrub tests (take 2)

### PR DESCRIPTION
**Pull request by dachary**

### CODE REVIEW

**Comment by dachary** [comment]
running a test to make sure no mistake was inserted ;-)

**Comment by dzafman** [comment]
You only have 7 of 8 commits from before.

**Comment by dachary** [comment]
@dzafman is this better ? This series is the one you rebased on, with a fix for the missing trailing space in the prefix variable as well as a s/ceph_objectstore_tool/ceph-objectstore-tool/ that was missing in https://github.com/dachary/ceph-qa-suite/commit/5c186e67a6e153ce8c531df77d96a5edd8bc5ef5

**Comment by dzafman** [comment]
Somehow you got my change "Fix Thrasher kill_osd() to ignore pool going away" into a commit of yours.

**Comment by dachary** [comment]
@dzafman yes, that happened as part of the conflict resolutions related to pep8 changes. If I do not include your change, you'll have to resolve the conflict. I figured it would be better if I include the change instead but I can remove it if you prefer to resolve the conflict instead.

**Comment by dachary** [comment]
<pre>
./virtualenv/bin/teuthology --suite-path $HOME/software/ceph/ceph-qa-suite --owner loic@dachary.org ../ceph-qa-suite/suites/rados/basic/tasks/repair_test.yaml roles.yaml targets-other.yaml 
</pre>
completed successfully.

**Comment by dachary** [comment]
@dzafman this pull request now matches https://github.com/dzafman/ceph-qa-suite/compare/wip-10018-scrub-new exactly, thanks for cleaning it up. Running the tests again.

**Comment by dachary** [comment]
tests run ok

**Pull request merged**
