### PR TITLE
DNM - Removed f-h-x-offline, tiering and v0-94-4-stop tests from runs on…

### PR DESCRIPTION
**Pull request by yuriw**
…jewel release

@liewegas @jdurgin @tmuthamizhan @athanatos 

Pls validate my assumption that those tests do not apply to jewel release, review and merge

Signed-off-by: Yuri Weinstein <yweinste@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
I think they do.  The problem is that debian will not ship a stable hammer, and hammer is a required upgrade from firefly -> (infernalis or jewel). They will eventually ship jewel in their next stable release.  We need to ensure that you can still upgrade by simply stopping all the firefly daemons and then starting the jewel ones.

**Comment by liewegas** [comment]
same goes for v0-94-4 (keep it).  not sure what the tiering test was for.

**Comment by yuriw** [comment]
@sage - ack I will close this PR then after checking on tireing part.  Can those two run on distors (centos + trusty)?

**Comment by liewegas** [comment]
Pretty sure, yep

**Pull request closed without merging**
