### PR TITLE
add erasure code and cache agent upgrade tests

### PR DESCRIPTION
**Pull request by dachary**
Signed-off-by: Loic Dachary <loic@dachary.org>

### CODE REVIEW

**Comment by yuriw** [comment]
@dachary - Do we need to add it to giant-x as well?

**Comment by dachary** [comment]
@yuriw we probably want that for giant-x as well indeed. I'll add it.

**Comment by dachary** [comment]
will reopen with a better version

**Comment by yuriw** [comment]
@dachary looks good, should I merge or it's still DNM?

**Comment by dachary** [comment]
@yuriw still testing. I was about to schedule it when various environmental problems such as diner interfered ;)

**Comment by dachary** [comment]
<pre>
./virtualenv/bin/teuthology-suite --filter 'upgrade:firefly-x:stress-split-erasure-code/{0-cluster/start.yaml 1-firefly-install/firefly.yaml 2-workload/ec-cache-create.yaml 3-partial-upgrade/firsthalf.yaml 4-thrash/default.yaml 5-mon/mona.yaml 6-workload/ec-cache-agent.yaml 7-next-mon/monb.yaml 8-next-mon/monc.yaml 9-workload/ec-no-lrc.yaml distros/ubuntu_14.04.yaml}' --suite-branch wip-ec-cache-agent --priority 101 --suite upgrade/firefly-x/stress-split-erasure-code --machine-type vps --email loic@dachary.org --owner loic@dachary.org --ceph hammer
</pre>

testing at http://pulpito.ceph.com/loic-2015-03-24_20:42:44-upgrade:firefly-x:stress-split-erasure-code-hammer---basic-vps/

**Comment by dachary** [comment]
it reproduces http://tracker.ceph.com/issues/11156 and should be merged when it's backported to firefly

**Pull request merged**
