### PR TITLE
tasks/ceph: fix up whitespace

### PR DESCRIPTION
**Pull request by jcsp**
...because otherwise it lights up like a christmas
tree in pycharm.

Signed-off-by: John Spray john.spray@redhat.com

### CODE REVIEW

**Comment by dachary** [comment]
@jcsp did you check that it backports cleanly on hammer ? That would help avoid whitespace related backport conflicts.

**Comment by jcsp** [comment]
@dachary cherry picking onto hammer isn't 100% clean, but the conflicts are pretty simple (the log rotation stuff that was added, the waiting for MDS to be healthy, and a couple of argument-indentations.  It shouldn't make it significantly harder to backport anything else

**Comment by dachary** [comment]
@jcsp will you cherry-pick to infernalis & hammer or would you like me to do it ?

**Comment by jcsp** [comment]
@dachary created backport PRs:

https://github.com/ceph/ceph-qa-suite/pull/745
https://github.com/ceph/ceph-qa-suite/pull/746

**Comment by dachary** [comment]
great thanks !

**Pull request merged**
