### PR TITLE
Initial checkin for hammer-x suite

### PR DESCRIPTION
**Pull request by yuriw**
Signed-off-by: Yuri Weinstein <yuri.weinstein@inktank.com>

### CODE REVIEW

**Comment by yuriw** [comment]
@dachary Pls take a look

**Comment by dachary** [comment]
It looks good to me. What is the diff with giant-x ?

**Comment by yuriw** [comment]
@dachary the only diff it starts off with hammer install

**Comment by dachary** [comment]
@yuriw :+1: then :-)

**Comment by yuriw** [comment]
@liewegas 
@tmuthamizhan 
@jdurgin 

Pls take a look

**Comment by tmuthamizhan** [comment]
looks good!

**Comment by tmuthamizhan** [comment]
looks good!

**Pull request merged**
