### PR TITLE
tasks: add TestSessionMap.test_[mount|tell]_conn_close

### PR DESCRIPTION
**Pull request by jcsp**
To check that teardown is happening correctly when
sending commands to an MDS.

Fixes: #14048
Signed-off-by: John Spray <john.spray@redhat.com>

### CODE REVIEW

**Comment by jcsp** [comment]
Related patch: https://github.com/ceph/ceph/pull/6933

**Comment by gregsfortytwo** [comment]
The commits on this branch look a little weird with the merges, which ones are supposed to be in it?

**Comment by jcsp** [comment]
Don't know what happened there.  Repushed this with just the right commit.

**Comment by jcsp** [comment]
Here it is running http://qa-proxy.ceph.com/teuthology/jspray-2016-01-13_01:39:24-fs:recovery-jewel---basic-mira/26640/teuthology.log

**Comment by gregsfortytwo** [comment]
http://pulpito.ceph.com/gregf-2016-01-18_18:01:09-fs-greg-fs-testing-118-1---basic-mira/

**Pull request merged**
