### PR TITLE
Added singleton hammer-x test to address #12625

### PR DESCRIPTION
**Pull request by yuriw**
@athanatos @liewegas - does this address what we discussed, e.g running simplified one-off hammer-x test during master branch  nightlies runs?

Signed-off-by: Yuri Weinstein <yweinste@redhat.com>

### CODE REVIEW

**Comment by liewegas** [comment]
It should go into the rados suite

**Comment by liewegas** [comment]
oh, it is :)

**Comment by yuriw** [comment]
yup - it's in /suites/rados/upgrade/hammer-x-sigleton/

**Comment by liewegas** [comment]
aside from the typo (singleton, not sigleton) it looks good to me

**Comment by yuriw** [comment]
fixed typo

**Comment by yuriw** [comment]
@athanatos test run http://pulpito.ceph.com/teuthology-2015-08-07_17:07:34-rados:upgrade-master-distro-basic-vps/

**Pull request merged**
