### PR TITLE
rados/multimon: Rewrite clock skew test

### PR DESCRIPTION
**Pull request by adamemerson**
As we are removing the clock skew parameter, actually skew the system clock.

### CODE REVIEW

**Comment by liewegas** [comment]
I think we can easily replace this with an equivalent test.  Combine it with teh other yaml fragments and put it in the rados/singleton/ dir somewhere, put the mon.b on a separate host, and add something like

<pre>
- exec:
    mon.b:
      - date --set ...
</pre>
the hard part is figuring out the current time + 10 seconds...

**Comment by tchaikov** [comment]
@liewegas shall we remove this tests or shall we wait until we have a replacement of this test which does not rely on the clock skew setting?

**Comment by liewegas** [comment]
I would prefer to fix the test now or else we'll forget.  I think it's 
pretty straightforward.. hard part is just writing a shell command to fast 
forward the clock

**Comment by adamemerson** [comment]
I'll make a replacement test, I'm just trying to get my Sepia access fixed, I think I lost my VPN credentials when reinstalling and I've been trying to see if I have them somewhere.

**Comment by liewegas** [comment]
ceph-qa-suite is now merged into ceph.git.  Please resubmit this PR against ceph.git.

**Pull request closed without merging**
