### PR TITLE
DNM: ceph-disk: add xenial

### PR DESCRIPTION
**Pull request by dachary**
Signed-off-by: Loic Dachary ldachary@redhat.com

### CODE REVIEW

**Comment by tchaikov** [comment]
@dachary have we run the ceph-disk task with xenial ? and it passed?

**Comment by dachary** [comment]
I don't think we did. This should not be merged until we have a clean run.

**Comment by liewegas** [comment]
any update here?

**Comment by dachary** [comment]
this already is implemented, closing. Ceph-disk routinely passes xenial.

**Pull request closed without merging**
