### PR TITLE
[DNM] Hammer s3debug

### PR DESCRIPTION
**Pull request by theanalyst**
For testing the DNSError issue, PR for reference

### CODE REVIEW

**Comment by dachary** [comment]
is there a difference between the hammer branch of s3test and the master branch of s3test ? In other words, do you need a wip-boto-debug-hammer branch that fixes things for hammer instead of master ?

**Comment by theanalyst** [comment]
@dachary updated this pr to do that, just rebased the wip-boto-debug atop of hammer in s3tests, pushed the branch

**Comment by theanalyst** [comment]
```ceph-workbench --verbose ceph-qa-suite --simultaneous-jobs 20 --suite rgw --ceph-git-url http://github.com/ceph/ceph --ceph hammer-backports --ceph-qa-suite-git-url http://github.com/theanalyst/ceph-qa-suite --suite-branch hammer-s3debug --subset $(expr $RANDOM % 100)/100 --upload```
RUNNING http://149.202.180.141:8081/ubuntu-2016-04-06_11:54:20-rgw-hammer-backports---basic-openstack/

**Comment by theanalyst** [comment]
Second run:
http://149.202.180.141:8081/ubuntu-2016-04-07_08:15:03-rgw-hammer-backports---basic-openstack/

we still have failures, but this was because gevent was still 0.13 in couple of runs as force-branch was not honored in the test-suite, the other failure was related to valgrind failures. All s3-tests with gevent>1.0 still pass

**Comment by liewegas** [comment]
ceph-qa-suite is now merged into ceph.git.  Please resubmit this PR against ceph.git.

**Pull request closed without merging**
