### PR TITLE
rbd: tests with rbd_skip_partial_discard option enabled

### PR DESCRIPTION
**Pull request by trociny**
Signed-off-by: Mykola Golub <mgolub@mirantis.com>

### CODE REVIEW

**Comment by dillaman** [comment]
Would you mind combining the partial discard and copy-on-read config options into a new "config" directory where we just test no overrides, copy-on-read, and skip partial discard?

**Comment by dillaman** [comment]
@trociny

**Comment by trociny** [comment]
@dillaman sorry, I missed your note due to wrong mail filter.

Do you mean something like the new patch? I will squash it later.

**Comment by dillaman** [comment]
@trociny Perfect -- thx

**Comment by trociny** [comment]
@dillaman rebased

**Pull request merged**
