### PR TITLE
Added openstack config openstack.yaml

### PR DESCRIPTION
**Pull request by yuriw**
@dachary pls review

Signed-off-by: Yuri Weinstein yweinste@redhat.com

### CODE REVIEW

**Comment by dachary** [comment]
You want to move that file in the suite that needs it. Which one is it ?

**Comment by yuriw** [comment]
smoke, done

**Comment by dachary** [comment]
@yuriw could you check that this file is actually doing the right thing by running the job it is supposed to fix with **--suite  wip-openstack-fixes** ?

**Comment by yuriw** [comment]
@dachary running like:
teuthology@teuthology:~$ teuthology-suite -v -c master -m openstack -s smoke -k distro -p 70  --filter="smoke/1node/{clusters/fixed-1.yaml tasks/ceph-deploy.yaml}"
http://pulpito.ovh.sepia.ceph.com:8081/teuthology-2015-10-19_20:17:17-smoke-master-distro-basic-openstack/

**Comment by dachary** [comment]
What about
<pre>
teuthology-suite -v -c master -m openstack -s smoke -k distro -p 70 --filter="smoke/1node/{clusters/fixed-1.yaml tasks/ceph-deploy.yaml}" --suite-branch wip-openstack-fixes 
</pre>

**Comment by yuriw** [comment]
failed seemingly due to unrelated reasons, rerunning
rerunning
<pre>
teuthology-suite -v -c master -m openstack -s smoke -k distro -p 70 --filter="smoke/1node/{clusters/fixed-1.yaml tasks/ceph-deploy.yaml}" --suite-branch wip-openstack-fixes
</pre>

http://pulpito.ovh.sepia.ceph.com:8081/teuthology-2015-10-19_22:01:33-smoke-master-distro-basic-openstack/

**Comment by dachary** [comment]
You need to **smoke/1node/clusters/+** and then **--dry-run** to find the description of the job you need to verify it works.

**Comment by yuriw** [comment]
Rerunning again http://pulpito.ovh.sepia.ceph.com:8081/teuthology-2015-10-19_22:38:01-smoke:1node-master-distro-basic-openstack/

**Pull request merged**
