### PR TITLE
Create ceph-mgr tests

### PR DESCRIPTION
**Pull request by jcsp**
This is an adaptation of the classes used for cephfs functional tests, to use them for ceph-mgr (https://github.com/ceph/ceph/pull/10328)

The body of REST API tests from the calamari tree will get ported into this framework.

### CODE REVIEW

**Comment by tchaikov** [comment]
looks sane. will give it a try later on.

**Comment by jcsp** [comment]
Passing here: http://pulpito.ceph.com/jspray-2016-10-19_21:12:28-mgr-master-distro-basic-mira/

**Comment by jcsp** [comment]
Weirdly this said it had a confict in tasks/ceph.py, but when I rebased it went through without needing manual intervention ¯\_(ツ)_/¯

**Comment by jcsp** [comment]
Related: https://github.com/ceph/teuthology/pull/971

**Comment by jcsp** [comment]
@tchaikov these should be good to go now

**Comment by tchaikov** [comment]
@jcsp sorry for the latency, needs rebase, and the it's good to merge.

**Comment by jcsp** [comment]
rebased this

**Pull request merged**
