### PR TITLE
cephfs/test_client_limits.py: invalidate kernel dcache according to c…

### PR DESCRIPTION
**Pull request by ukernel**
…lient_cache_size

Signed-off-by: Yan, Zheng <zyan@redhat.com>

### CODE REVIEW

**Comment by jcsp** [comment]
:+1: looks great, should merge as soon as https://github.com/ceph/ceph/pull/4653

**Comment by gregsfortytwo** [comment]
This looks good as far as it goes. But like I said in https://github.com/ceph/ceph/pull/4653, I'd really like to see this including checks on the MDS's cache pressure requests. Is that infeasible for some reason?

**Comment by ukernel** [comment]
On Thu, May 14, 2015 at 5:23 AM, Gregory Farnum <notifications@github.com>
wrote:

> This looks good as far as it goes. But like I said in ceph/ceph#4653
> <https://github.com/ceph/ceph/pull/4653>, I'd really like to see this
> including checks on the MDS's cache pressure requests. Is that infeasible
> for some reason?
>
there already is test case for MDS's cache pressure. I don't like the idea
that testing multiple functions in single test case.

**Comment by jcsp** [comment]
@gregsfortytwo the MDS-driven cache pressure is orthogonal to this (it's the Client::trim_caps path, this is about the Client::trim_cache path)

**Comment by gregsfortytwo** [comment]
Oh, I guess we are doing the kernel invalidate in trim_caps already.

**Comment by gregsfortytwo** [comment]
Running in greg-fs-testing as a final check.

**Pull request merged**
