### PR TITLE
hammer: min_write_recency_for_promote does not exist in hammer

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
http://tracker.ceph.com/issues/15301

### CODE REVIEW

**Comment by dachary** [comment]
test this please

**Comment by dachary** [comment]
<code>ceph-workbench --verbose ceph-qa-suite --suite rados --ceph-qa-suite-git-url http://github.com/Vicente-Cheng/ceph-qa-suite --suite-branch wip-15301-hammer --ceph-git-url http://github.com/ceph/ceph --ceph hammer-backports --filter='rados/thrash/{0-size-min-size-overrides/2-size-2-min-size.yaml 1-pg-log-overrides/normal_pg_log.yaml clusters/{fixed-2.yaml openstack.yaml} fs/xfs.yaml msgr-failures/fastclose.yaml thrashers/default.yaml workloads/cache-agent-big.yaml}'</code>

* *running* http://167.114.252.97:8081/ubuntu-2016-03-29_16:37:30-rados-hammer-backports---basic-openstack/

**Comment by dachary** [comment]
<pre>
2016-03-29T16:56:57.108 INFO:tasks.rados.rados.0.target167114225078.stdout:800:  finishing write tid 5 to target167114225078.teuthology11099-800
2016-03-29T16:56:57.108 INFO:tasks.rados.rados.0.target167114225078.stderr:Error: oid 800 write returned error code -5
2016-03-29T16:56:57.115 INFO:tasks.rados.rados.0.target167114225078.stderr:Error: oid 800 write returned error code -5
2016-03-29T16:56:57.115 INFO:tasks.rados.rados.0.target167114225078.stderr:Error: racing read on 800 returned version 0 rather than version 1005
2016-03-29T16:56:57.115 INFO:tasks.rados.rados.0.target167114225078.stderr:./test/osd/RadosModel.h: In function 'virtual void WriteOp::_finish(TestOp::CallbackInfo*)' thread 7f7c757fa700 time 2016-03-29 16:56:57.060109
2016-03-29T16:56:57.115 INFO:tasks.rados.rados.0.target167114225078.stderr:./test/osd/RadosModel.h: 881: FAILED assert(0 == "racing read got wrong version")
2016-03-29T16:56:57.115 INFO:tasks.rados.rados.0.target167114225078.stderr: ceph version 0.94.6-259-g8cc324d (8cc324df4caf0d043208d9abe88a0e217e861dc3)
2016-03-29T16:56:57.115 INFO:tasks.rados.rados.0.target167114225078.stderr: 1: (ceph::__ceph_assert_fail(char const*, char const*, int, char const*)+0x8b) [0x4e101b]
2016-03-29T16:56:57.116 INFO:tasks.rados.rados.0.target167114225078.stderr: 2: (WriteOp::_finish(TestOp::CallbackInfo*)+0x3d4) [0x4c8d34]
2016-03-29T16:56:57.116 INFO:tasks.rados.rados.0.target167114225078.stderr: 3: (write_callback(void*, void*)+0x19) [0x4d8619]
2016-03-29T16:56:57.116 INFO:tasks.rados.rados.0.target167114225078.stderr: 4: (()+0x950ed) [0x7f7c821200ed]
2016-03-29T16:56:57.116 INFO:tasks.rados.rados.0.target167114225078.stderr: 5: (()+0x70439) [0x7f7c820fb439]
2016-03-29T16:56:57.116 INFO:tasks.rados.rados.0.target167114225078.stderr: 6: (()+0x134438) [0x7f7c821bf438]
2016-03-29T16:56:57.116 INFO:tasks.rados.rados.0.target167114225078.stderr: 7: (()+0x8182) [0x7f7c81c5f182]
2016-03-29T16:56:57.116 INFO:tasks.rados.rados.0.target167114225078.stderr: 8: (clone()+0x6d) [0x7f7c805e447d]
2016-03-29T16:56:57.116 INFO:tasks.rados.rados.0.target167114225078.stderr: NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.
2016-03-29T16:56:57.116 INFO:tasks.rados.rados.0.target167114225078.stderr:terminate called after throwing an instance of 'ceph::FailedAssertion'
2016-03-29T16:56:57.116 INFO:tasks.rados.rados.0.target167114225078.stdout:update_object_version oid 800 v 1005 (ObjNum 799 snap 0 seq_num 799) dirty exists
</pre>

**Comment by liewegas** [comment]
was https://github.com/ceph/ceph/pull/8187 included?

**Comment by dachary** [comment]
running again with https://github.com/ceph/ceph/pull/8187 (thanks @liewegas ;-) 

<code>ceph-workbench --verbose ceph-qa-suite --suite rados --ceph-qa-suite-git-url http://github.com/Vicente-Cheng/ceph-qa-suite --suite-branch wip-15301-hammer --ceph-git-url http://github.com/liewegas/ceph --ceph wip-15171 --filter='rados/thrash/{0-size-min-size-overrides/2-size-2-min-size.yaml 1-pg-log-overrides/normal_pg_log.yaml clusters/{fixed-2.yaml openstack.yaml} fs/xfs.yaml msgr-failures/fastclose.yaml thrashers/default.yaml workloads/cache-agent-big.yaml}'</code>

* *running* http://167.114.252.97:8081/ubuntu-2016-03-29_19:53:23-rados-wip-15171---basic-openstack/

**Comment by dachary** [comment]
the test fails but actually completes successfully but the cluster does not come back to a clean state when unwinding the thrashosd.

<pre>
2016-03-29T21:22:30.278 INFO:tasks.rados.rados.0.target167114227065.stderr:0 errors.
2016-03-29T21:22:30.279 INFO:tasks.rados.rados.0.target167114227065.stderr:
2016-03-29T21:22:30.291 DEBUG:teuthology.run_tasks:Unwinding manager thrashosds
2016-03-29T21:22:30.303 INFO:tasks.thrashosds:joining thrashosds
...
ubuntu@target167114227065:~$ sudo ceph -s
    cluster 5d792e64-8050-4f6e-908c-8df3060d7e8d
     health HEALTH_WARN
            1 pgs backfill
            1 pgs backfilling
            3 pgs degraded
            1 pgs recovering
            2 pgs recovery_wait
            3 pgs stuck degraded
            5 pgs stuck unclean
            recovery 5859/23854 objects degraded (24.562%)
            recovery 3145/23854 objects misplaced (13.184%)
            pool rbd pg_num 64 > pgp_num 34
            mon.b has mon_osd_down_out_interval set to 0
     monmap e1: 3 mons at {a=167.114.227.65:6789/0,b=167.114.227.66:6789/0,c=167.114.227.65:6790/0}
            election epoch 4, quorum 0,1,2 a,b,c
     osdmap e102: 6 osds: 6 up, 6 in; 2 remapped pgs
      pgmap v1691: 72 pgs, 3 pools, 24548 MB data, 8609 objects
            44129 MB used, 136 GB / 179 GB avail
            5859/23854 objects degraded (24.562%)
            3145/23854 objects misplaced (13.184%)
                  67 active+clean
                   2 active+recovery_wait+degraded
                   1 active+recovering+degraded
                   1 active+remapped+backfilling
                   1 active+remapped+wait_backfill
recovery io 12294 kB/s, 4 objects/s
</pre>

**Comment by dachary** [comment]
The failure is not familiar to Sam, created a bug at http://tracker.ceph.com/issues/15313 to track it down.

**Comment by dachary** [comment]
I was just not patient enough, the recovery makes progress and eventually completes.

**Pull request merged**
