### PR TITLE
suites/multimds: sync with fs suites

### PR DESCRIPTION
**Pull request by batrick**
This commit synchronizes the multimds suite with the fs suite. The basic/verify
sub-suites now do the same tests except with different cluster layouts (i.e.
multiple actives). This is mostly accomplished by symlinking parts of each
sub-suite to its counterpart in the fs suite. 

This commit also does a few things of note to the prior multimds suite:

o Turn on directory fragmentation.
o Add several tests from fs/basic/tasks to multimds/basic.
o Remove libcephfs as fs/basic/tasks already contain
  multimds/basic/tasks.

Prior implementation and discussion are in PR#1114: https://github.com/ceph/ceph-qa-suite/pull/1114

### CODE REVIEW

**Comment by batrick** [comment]
Here's a recent large run (from a slightly older version of this PR):

http://pulpito.front.sepia.ceph.com/pdonnell-2016-11-30_05:59:07-multimds-master-testing-basic-mira/

Here's a followup which fixes a bug where kclient needs to be unmounted for libcephfs tests:

http://pulpito.front.sepia.ceph.com/pdonnell-2016-12-02_01:20:51-multimds-master-testing-basic-mira/

I'm trying to do another multimds run with this current PR but gitbuilders seems to be having issues. I'll keep trying and add a comment when I have another run.

**Comment by batrick** [comment]
I forgot to mention: this PR is based on #1282 which should be merged before this.

**Comment by jcsp** [comment]
@batrick sage modified some valgrind.yaml files to pin things to centos, so this needs a rebase

**Comment by batrick** [comment]
@jcsp I would prefer to wait until after #1282 is merged (which doesn't need rebase).

**Comment by batrick** [comment]
Latest test run: http://pulpito.ceph.com/pdonnell-2016-12-05_17:42:01-multimds-wip-multimds-tests-testing-basic-mira/

**Comment by jcsp** [comment]
@batrick #1282 merged now

**Comment by batrick** [comment]
@jcsp rebased!

**Pull request merged**
