### PR TITLE
Smarter s3tests branch selection

### PR DESCRIPTION
**Pull request by yuriw**
Signed-off-by: Zack Cerza <zack.cerza@inktank.com>
(cherry picked from commit 1b8d31986a5a8bc4cd9fea90eb680db3ca1866c8)

Conflicts:

	tasks/s3tests.py

Signed-off-by: Yuri Weinstein <yuri.weinstein@inktank.com>

### CODE REVIEW

**Comment by yuriw** [comment]
@yehudasa FYI
@zmc  pls review

**Comment by dachary** [comment]
@yuriw FYI there is a merge conflict in your patch

**Comment by dachary** [comment]
assuming the intended change is https://github.com/ceph/ceph-qa-suite/pull/306/files#diff-f629596e81d9e0130affbf21f2a663deR129 it looks good to me. 
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Comment by zmc** [comment]
Why remove that whitespace?

Also this should be squashed into one commit

**Pull request closed without merging**
