### PR TITLE
add divergent priors tests

### PR DESCRIPTION
**Pull request by dzafman**
Testing changes ceph/ceph#7702.  Should get merged at the same time.

### CODE REVIEW

**Comment by dachary** [comment]
@dzafman LGTM, could you add a link to the matching teuthology run here ?

**Comment by dzafman** [comment]
As of this moment tests are still running:  http://pulpito.ceph.com/dzafman-2016-02-24_12:11:35-rados-wip-14077-hammer---basic-smithi/

There is 1 failure so far, so I think I need to cherry-pick another master change to suites/rados/singleton/all/pg-removal-interruption.yaml  (07232b1e2bed5911453f30397a5a9de6c9d3125d)

**Comment by dzafman** [comment]
After adding back ported 2 more commits to this pull requests.  I ran just the rados/singleton/all to show that the one failure in the rados run above is fixed.

http://pulpito.ceph.com/dzafman-2016-02-24_20:32:40-rados:singleton:all-wip-14077-hammer---basic-smithi/

Only failure is already an existing bug http://tracker.ceph.com/issues/12814

**Comment by dachary** [comment]
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Pull request merged**
