### PR TITLE
DNM (see 'waiting on' comment): ceph-deploy bluestore test option

### PR DESCRIPTION
**Pull request by vasukulkarni**
Add bluestore test option to ceph-deploy

### CODE REVIEW

**Comment by dachary** [comment]
sorry I don't know enough about ceph-deploy to review

**Comment by vasukulkarni** [comment]
Waiting on http://tracker.ceph.com/issues/15397

**Comment by dmick** [comment]
@dachary this was all about ceph-qa-suite, but yes, need to make sure the bluestore args are correct

**Comment by dachary** [comment]
@dmick I mean I don't know enough about the ceph-deploy suite nor ceph-deploy. The --bluestore option is good for ceph-disk but I don't know how / if ceph-deploy supports it.

**Comment by dmick** [comment]
@vasukulkarni what's the status of this?  Do we still need this PR?

**Comment by vasukulkarni** [comment]
@dmick closing this for now, since ceph-disk part is still in works, will test later after its complete.

**Pull request closed without merging**
