### PR TITLE
tasks: add rebuild_mondb

### PR DESCRIPTION
**Pull request by tchaikov**
* tasks/rebuild_mondb.py: this task
  1. removes all store.db on all monitors
  2. rebuild the store.db for the first mon
  3. start the first mon
  4. run mkfs on other mon
  5. and revive them
* suites/rados/singleton/all/rebuild-mon-db.yaml
  1. run rados/test.sh
  2. run rebuild_mondb task

Fixes: http://tracker.ceph.com/issues/17179
Signed-off-by: Kefu Chai <kchai@redhat.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
tested at http://pulpito.ceph.com/kchai-2016-09-08_11:09:56-rados:singleton-wip-kefu-testing---basic-mira/405296/.

**Comment by tchaikov** [comment]
@athanatos, could you a look at https://github.com/ceph/ceph/pull/10933 again? i think i've addressed the discontinuous osdmap scenario.

**Comment by athanatos** [comment]
LGTM!

**Comment by tchaikov** [comment]
will merge it once ceph/ceph#10933 is merged.

**Pull request merged**
