### PR TITLE
Add TestConfigCommands for #14365 

### PR DESCRIPTION
**Pull request by jcsp**

### CODE REVIEW

**Comment by jcsp** [comment]
This tests ceph PR: https://github.com/ceph/ceph/pull/7312

**Comment by gregsfortytwo** [comment]
You reviewed this while looking at the Ceph PR, right @ukernel? :)

**Comment by gregsfortytwo** [comment]
@jcsp:

>gregf@rex004:~/src/ceph-qa-suite [master]$ pyflakes tasks/cephfs/test_config_commands.py 
tasks/cephfs/test_config_commands.py:5: 'CommandFailedError' imported but unused

**Comment by gregsfortytwo** [comment]
Drat, I'm sorry @jcsp, but I missed a test failure when I merged the ceph branch (and forgot to merge this one). Running it in my latest test branch I'm seeing an assert in http://pulpito.ceph.com/gregf-2016-02-03_09:19:17-fs-greg-fs-testing-23---basic-mira/4588

>existing dependency Client::client_lock (12) -> Objecter::rwlock (14) at:
2016-02-03 21:09:35.145789 7fcb11af5e80  0 existing intermediate dependency AdminSocket::m_lock (1) -> Client::client_lock (12) at:
2016-02-03 21:09:35.147807 7fcb11af5e80  0 new dependency Objecter::rwlock (14) -> AdminSocket::m_lock (1) creates a cycle at
 ceph version 10.0.2-1645-g4daa934 (4daa934e6d2d50754149a876fb8bf5cef1f6c71d)
 1: (AdminSocket::unregister_command(std::string)+0x3c) [0x7fcb1168655c]
 2: (Objecter::shutdown()+0x6da) [0x7fcb1158a89a]
 3: (Client::shutdown()+0x5ea) [0x7fcb114c36aa]
 4: (main()+0x5d9) [0x7fcb114b03c9]
 5: (__libc_start_main()+0xf5) [0x7fcb0f35dec5]
 6: (()+0x177bb7) [0x7fcb114b3bb7]

And I also saw it on the previous test run: http://pulpito.ceph.com/gregf-2016-01-26_15:35:20-fs-greg-fs-testing-126---basic-mira/44982

Can you check that out and submit another PR to clean it up?

**Comment by jcsp** [comment]
Related fix:
https://github.com/ceph/ceph/pull/7581

**Pull request merged**
