### PR TITLE
ceph_manager: test offline split via ceph-objectstore-tool

### PR DESCRIPTION
**Pull request by jdurgin**
When killing an osd, split all pools with a low threshold.
This will slow down tests, but should not impact correctness.

Signed-off-by: Josh Durgin <jdurgin@redhat.com>
(cherry picked from commit f28f881bda0ad426bfa9c0e22cc4658b2ce2ec5d)

### CODE REVIEW

**Comment by jdurgin** [comment]
this tests https://github.com/ceph/ceph/pull/11252

**Comment by smithfarm** [comment]
@jdurgin This breaks the infernalis-x upgrade suite: http://tracker.ceph.com/issues/17683

We would need to conditionalize this block of code so it only runs if jewel or higher is installed on the test machine.

**Comment by jdurgin** [comment]
@smithfarm if we still want to run the infernalis-x suite, adding an option to ceph_manager to disable this test and setting that in the infernalis-x suite sounds like a reasonable workaround to me.

This was backported to hammer too, so checking for version is a bit more complicated. Infernalis was only skipped since it's eol.

**Comment by smithfarm** [comment]
@jdurgin Like this? https://github.com/ceph/ceph-qa-suite/pull/1252

**Pull request merged**
