### PR TITLE
rados: remove btrfs tests; use xfs instead

### PR DESCRIPTION
**Pull request by liewegas**
Signed-off-by: Sage Weil <sage@redhat.com>

### CODE REVIEW

**Comment by athanatos** [comment]
lgtm

**Comment by tchaikov** [comment]
@liewegas are we dropping the support of btrfs as one of filestore backends?

**Comment by smithfarm** [comment]
@liewegas A stray coredump got into the wip branch `suites/rados/upgrade/jewel-x-singleton/1-jewel-install/core.29886.29886` - can you remove?

**Comment by smithfarm** [comment]
I'm in favor of dropping the btrfs tests in hammer. I am still in the process of testing 0.94.10 and the btrfs failures are not making the task any easier. Also, not having the btrfs will simplify testing of post-0.94.10 hammer releases, should there be any.

**Pull request merged**
