### PR TITLE
s3tests using ec data pool for smoke

### PR DESCRIPTION
**Pull request by vasukulkarni**
Add s3tests using ec data pool

Signed-off-by: Vasu Kulkarni <vasu@redhat.com>

### CODE REVIEW

**Comment by vasukulkarni** [comment]
@yehudasa we can add this to smoke and will get tested early enough during wip since rgw is a bigger suite.

**Comment by vasukulkarni** [comment]
@yehudasa : do you think it makes sense to add this to smoke? s3 test with ec data pool and civetweb.

**Comment by yehudasa** [comment]
@vasukulkarni yeah, we can put it in the smoke test

**Comment by vasukulkarni** [comment]
@yehudasa thanks, I have tested this.

**Pull request merged**
