### PR TITLE
buildpackages: make make-{deb,rpm}.sh aware of cmake

### PR DESCRIPTION
**Pull request by rjfd**
This is the followup of an existing PR #1131 

Fixes: http://tracker.ceph.com/issues/16819

Signed-off-by: Ricardo Dias rdias@suse.com
Signed-off-by: Nathan Cutler ncutler@suse.com

### CODE REVIEW

**Comment by dachary** [comment]
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

as soon as the checks come back clean.

**Comment by smithfarm** [comment]
`cw -v ceph-qa-suite --simultaneous-jobs 10 --teuthology-git-url http://github.com/SUSE/teuthology --teuthology-branch wip-opensuse --ceph-qa-suite-git-url http://github.com/rjfd/ceph-qa-suite --suite-branch wip-16819 --suite buildpackages/any --filter 'ubuntu_14.04.yaml'`

**pass** http://149.202.172.244:8081/ubuntu-2016-08-24_16:46:07-buildpackages:any-master---basic-openstack/

`cw -v ceph-qa-suite --simultaneous-jobs 10 --teuthology-git-url http://github.com/SUSE/teuthology --teuthology-branch wip-opensuse --ceph-qa-suite-git-url http://github.com/rjfd/ceph-qa-suite --suite-branch wip-16819 --suite buildpackages/any --filter 'ubuntu_14.04.yaml'`

**pass** http://149.202.172.244:8081/ubuntu-2016-08-24_14:26:25-buildpackages:any-master---basic-openstack/

**Comment by dachary** [comment]
@rjfd @smithfarm awesome work, thanks !

**Comment by smithfarm** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;rfyNDkDU&#x2F;1922-issue-16819-buildpackages-make-deb-sh-does-not-support-cmake"> (issue#16819) buildpackages (make-deb.sh) does not support cmake</a>

**Pull request merged**
