### PR TITLE
[DNM] s3readwrite: set debug level to 2 for boto

### PR DESCRIPTION
**Pull request by theanalyst**
This is for debugging the dns issue, let us crank up logging with boto
and see if we can find the cause of the issue

Signed-off-by: Abhishek Lekshmanan abhishek@suse.com

### CODE REVIEW

**Comment by theanalyst** [comment]
So the force-branch option in s3tests yaml allow for a custom branch.. an example is shown in https://github.com/ceph/ceph-qa-suite/blob/master/suites/teuthology/rgw/tasks/s3tests-fcgi.yaml#L15

So as a hack i guess we can just pass this onto the yaml creation stage in this file itself.. @dachary wdyt

**Comment by dachary** [comment]
@theanalyst yes. Which test would you like me to run with this branch ?

**Comment by dachary** [comment]
<code>ceph-workbench --verbose ceph-qa-suite --ceph-git-url http://github.com/dachary/ceph --ceph jewel --ceph-qa-suite-git-url  http://github.com/theanalyst/ceph-qa-suite --suite-branch wip-s3rw --filter='rados/thrash/{hobj-sort.yaml rados.yaml 0-size-min-size-overrides/3-size-2-min-size.yaml 1-pg-log-overrides/short_pg_log.yaml clusters/{fixed-2.yaml openstack.yaml} fs/xfs.yaml msgr/simple.yaml msgr-failures/osd-delay.yaml thrashers/pggrow.yaml workloads/rgw_snaps.yaml}' --suite rados</code>

* *running* http://167.114.242.130:8081/ubuntu-2016-04-05_11:58:41-rados-jewel---basic-openstack/

**Comment by theanalyst** [comment]
Second run with rgw in debug mode.. http://149.202.162.122/ubuntu-2016-04-05_16:30:34-rados-jewel---basic-openstack/1/teuthology.log 
client logs (rgw etc) rgw log:http://149.202.162.122/ubuntu-2016-04-05_16:30:34-rados-jewel---basic-openstack/1/remote/target149202163023/log/

**Comment by theanalyst** [comment]
New run: http://149.202.162.122:8081/ubuntu-2016-04-06_07:52:31-rados-jewel---basic-openstack/ 

This contains the gevent fix upgrading gevent > 1.0

**Comment by liewegas** [comment]
ceph-qa-suite is now merged into ceph.git.  Please resubmit this PR against ceph.git.

**Pull request closed without merging**
