### PR TITLE
erasure coding: LRC thrasher & fast read thrasher

### PR DESCRIPTION
**Pull request by guangyy**
https://github.com/ceph/ceph-qa-suite/pull/445
https://github.com/ceph/ceph-qa-suite/pull/499

Signed-off-by: Guang Yang <yguang@yahoo-inc.com>

### CODE REVIEW

**Comment by guangyy** [comment]
@athanatos  @dachary

**Comment by dachary** [comment]
@guangyy Did you try to run it in a teuthology cluster already ?

**Comment by guangyy** [comment]
@dachary , sorry missing this one. Yes I did run in a teuthology cluster, guess we should merge together with https://github.com/ceph/ceph/pull/5309 :)

**Comment by dzafman** [comment]
ceph/ceph#5309 has merged.  I ran these changes against it and it was successful.

**Pull request merged**
