### PR TITLE
suites/smoke/1node: move + to clusters/ subdirectory

### PR DESCRIPTION
**Pull request by smithfarm**
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
@yuriw: Could you take a look?

**Comment by yuriw** [comment]
@smithfarm looks good, would you like to use annotations that can be used with @teuthology-describe-tests@ like in this suite https://github.com/ceph/ceph-qa-suite/tree/master/suites/upgrade/infernalis-x (look for @meta:@ tag)

**Comment by smithfarm** [comment]
@yuriw: Thanks for pointing that out! I am studying the suites now, so to the extent that I can decipher them I will look into add `meta:` stanzas where they are missing.

**Comment by yuriw** [comment]
@smithfarm that's be cool, note: there are not @missing@ it's a new concept to describe/annotate test cases and it's not widely used yet

**Comment by smithfarm** [comment]
@yuri So only in the master branch?

**Comment by yuriw** [comment]
@smithfarm well I do it on any named branch, but the cherry-pick to master and then we can create a  nice looking test plan like this 
http://tracker.ceph.com/projects/ceph-qa-suite/wiki/
http://tracker.ceph.com/projects/ceph-qa-suite/wiki/infernalis

**Comment by smithfarm** [comment]
@yuriw: Wow, that's cool!

**Comment by yuriw** [comment]
@smithfarm  :+1: 
There was an email from @jdurgin on this, in short the workflow is:
use `meta:` stanzas in the suites => parse + crontab + publish to the tracker wiki with `teuthology-describe-tests`

**Comment by smithfarm** [comment]
@yuriw That would be http://article.gmane.org/gmane.comp.file-systems.ceph.devel/29287

Don't know how I missed it?

**Pull request merged**
