### PR TITLE
(jewel) tasks/cephfs: test volume client eviction

### PR DESCRIPTION
**Pull request by ajarr**
Test whether the CephFSVolumeClient can evict a client based on its
auth ID and the volume path it has mounted.

Fixes: http://tracker.ceph.com/issues/15855

Signed-off-by: Ramana Raja <rraja@redhat.com>
(cherry picked from commit cbadb38)

### CODE REVIEW

**Comment by ajarr** [comment]
Test for https://github.com/ceph/ceph/pull/9221

**Comment by smithfarm** [comment]
@jcsp OK to merge this before we schedule a jewel integration run?

**Comment by jcsp** [comment]
@smithfarm you'll want to merge this at the same time as #9221

**Comment by jcsp** [comment]
Merged this as part of https://github.com/ceph/ceph-qa-suite/pull/1030

**Pull request closed without merging**
