### PR TITLE
git.ceph.com (firefly)

### PR DESCRIPTION
**Pull request by gregsfortytwo**
Signed-off-by: Sage Weil <sage@redhat.com>
(cherry picked from commit dafc19cc5ae671df01f975ea4e1958a5125ef982)

Conflicts:
	suites/rbd/librbd/workloads/qemu_fsstress.yaml
	suites/rbd/singleton/all/formatted-output.yaml

Signed-off-by: Greg Farnum <gfarnum@redhat.com>

### CODE REVIEW

**Comment by gregsfortytwo** [comment]
I picked this off of the firefly branch and the part I'm not sure about is the "h=giant" bit on the qemu_fsstress yaml. What does sticking that on the end of the git url do, and is it appropriate to make that change in this case?

**Comment by gregsfortytwo** [comment]
Never mind, Sage already did one of these at https://github.com/ceph/ceph-qa-suite/pull/411...

**Comment by liewegas** [comment]
this shows giant-ceph-git and targets giant but desc is firefly?
and there is this giant one: https://github.com/ceph/ceph-qa-suite/pull/411

**Comment by liewegas** [comment]
nm, i'm confused ;)

**Pull request closed without merging**
